首先，我们导入 `torch`。请注意，虽然它被称为 `PyTorch`，但我们应该导入 `torch` 而不是 `pytorch`。

In [1]:
import torch

张量表示一个数值组成的数组，这个数组可能有多个维度。

In [3]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

我们可以通过张量的 `shape` 属性来访问张量的形状和张量中元素的总数。

In [6]:
x.shape

torch.Size([12])

In [7]:
x.numel()

12

要改变一个张量的形状而不改变元素数量和元素值，我们可以调用 `reshape` 函数。

In [9]:
x.reshape(3, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

使用全0、全1、其它常量或者从特定分布中随机采样的数字

In [10]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

通过提供包含数值的 `Python` 列表（或嵌套列表）来为所需张量中的每个元素赋予确定值。

In [13]:
torch.tensor(([2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]))

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

常见的标准算术运算符（`+`、`-`、`*`、`/` 和 `**`）都可以被升级为按元素运算。

In [14]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y # ** 运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

按元素方式应用更多的计算

In [15]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

我们也可以把多个张量连结在一起

In [ ]:
x = torch.arange(12, dtype=torch.float32).reshape((3, 4))
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((x, y), dim=0), torch.cat((x, y), dim=1)

逻辑运算符构建二元张量

In [21]:
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

对张量中的所有元素进行求和会产生一个只有一个元素的张量

In [23]:
x.sum()

tensor(66.)

即使形状不同，但是维度相同，我们仍然可以通过调用广播机制来执行按元素操作。

In [24]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [25]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

可以用 `[-1]` 选择最后一个元素，可以用 `[1:3]` 选择第二个和第三个元素

In [27]:
x[-1], x[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

除读取外，我们还可以通过指定索引来将元素写入矩阵。

In [28]:
x[1, 2] = 9
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

为多个元素赋值相同的值，我们只需要索引所有元素，然后为它们赋值。

In [29]:
x[0:2, :] = 12
x

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

运行一些操作可能会导致为新结果分配内存

In [32]:
before = id(y)
y = y + x
id(y) == before

False

In [ ]:
z = torch.zeros_like(y)
print('id(x):', id(z))
z[:] = x + y
print('id(x):', id(z))

如果在后续计算中没有重复使用 x，我们也可以使用 x[:] = x + y 或 x += y 来减少操作的内存开销。

In [34]:
before = id(x)
x += y
id(x) == before

True

转换为 `NumPy` 张量

In [37]:
a = x.numpy()
b = torch.tensor(a)
type(a), type(b)

(numpy.ndarray, torch.Tensor)

将大小为 1 的张量转换为 Python 标量

In [38]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)